### ISSUE TITLE
Fail earlier at registration, not resolve

### ISSUE THREAD

**Issue by john-twigg-ck** [Swinject/SwinjectAutoregistration#17]
I see that the call to  
```checkResolved(...)```
is done at resolve time. If the registered initializer contains an optional, for example, it would fail long after its been registered.

Is there anyway the failure could occur at registration time, which is by definition going to occur earlier in the application life cycle?

This would decrease bugs I believe.

**Comment by tkohout** [comment]
Hello John,
thanks for taking an interest in the library. I see your point in failing upon registering the optional, implicitly unwrapped service or service with too many dependencies. The reason why the check is not done in registration is performance. To check the type we actually have to parse the result of `String(describing: Service.Type)` using a simple TypeParser. That would negatively affect performance if it would have to be done for every registered service. Second reason is that these warnings were only meant as hints when something fails. There might be false positives which would prevent registering otherwise perfectly fine services.
