### ISSUE TITLE
Allow using Optional dependencies

### ISSUE THREAD

**Issue by paulz** [Swinject/SwinjectAutoregistration#28]
It would be nice if we can use optional dependencies:

```
PersonOwner(name:String, pet: AnimalType?)
```
and
```
PersonOwner(name:String, pet: AnimalType!)
```

Can we have a resolver that tries to resolve optionals and falls back to nil?

**Comment by tkohout** [comment]
Hello @paulz , thanks for taking an interest in the library.

Unfortunately, it is not possible to achieve registering optional or unwrapped dependencies technically. If you look at the [source](https://github.com/Swinject/SwinjectAutoregistration/blob/master/Sources/AutoRegistration.swift#L241) you can see there are generated autoregister functions for up to 20 dependencies.

For your example with PersonOwner following function is used:
``` 
public func autoregister<Service, A, B>(_ service: Service.Type, name: String? = nil, initializer: @escaping (A, B) -> Service)
```
To be able to use it with optional service and unwrap it, you would also have to have
```
initializer: (A, B?) -> Service
```
But also
```
initializer: (A?, B) -> Service
```
and
```
initializer: (A?, B?) -> Service
```

This leads to large number of permutations for 20 dependencies (20!) both for Optional and ImplicitlyUnwrapped dependencies.

I also tried to cast and unwrap the dependencies in the existing functions but because we are working with types and not instances I think it is not currently possible.

**Comment by paulz** [comment]
Here is how we solved injecting optionals on our project:
```
import Swinject
import SwinjectAutoregistration

protocol WrappingProtocol {
    associatedtype Unwrapped
    init(_ some: Unwrapped)
}

extension ImplicitlyUnwrappedOptional : WrappingProtocol {
    typealias Unwrapped = Wrapped
}

extension Optional : WrappingProtocol {
    typealias Unwrapped = Wrapped
}

postfix func ~> <Service: WrappingProtocol>(r: Resolver) -> Service {
    return Service(r ~> Service.Unwrapped.self)
}
```

It allow us to injection optionals, for example:
```
        container.storyboardInitCompleted(AccountViewController.self) { r, c in
            c.account = r~>
            c.accountManager = r~>
            c.accountUpdater = r~>
        }
```

**Comment by paulz** [comment]
And thank you for such an awesome pod, I've been using it on the last 3 project with the great success!

**Comment by tkohout** [comment]
I am not a big fan of adding new conformance to the native optional type. I would rather prefer solution in the Swinject itself. You can upvote [this issue](https://github.com/Swinject/Swinject/issues/280) if you would like to have this functionality.

**Comment by paulz** [comment]
Maybe as an optional module like
`SwinjectResolveOptionals`

**Comment by jakubvano** [comment]
As of Swinject 2.3.0 resolution of the optional dependencies shoud work as described here, i.e 
```
container.autoregister(PersonOwner.self, initializer: PersonOwner.init)
// or
container.register(PersonOwner.self) {  PersonOwner(name: $0~>, pet: $0~> }
```
Will resolve `pet` to an instance if there is a registration for `Animal.self`, or to `nil` if there isn't one.

This should work transparently with current vesion of SwinjectAutoregistration (provided you update the Swinject version)
