### ISSUE TITLE
Framework size

### ISSUE THREAD

**Issue by mapo80** [Swinject/SwinjectAutoregistration#44]
Hi,

I've built framework using Carthage and I've seen thats its size is 7.021.260 bytes.
Swinject size is 5.009.531 bytes
SwinjectStoryboard is 1.253.881 bytes

I think there's an error. How to solve?

**Comment by tkohout** [comment]
Hello, sorry for the late answer.

This is likely not an error. There is quite a lot of code generated in order to make autoregistration work. We support up to 20 dependencies so there has to be at least 20 functions generated (see the https://github.com/Swinject/SwinjectAutoregistration/blob/master/Sources/AutoRegistration.swift). If this is a deal breaker for you, you could build a custom version of the framework with less dependencies. You can run for example `./bin/generate 10 3` which will generate framework up to 10 dependencies and 3 dynamic arguments.
