### ISSUE TITLE
SwinjectAutoregistration crashes on Xcode 12.0 (12A7209)

### ISSUE THREAD

**Issue by muratmusic** [Swinject/SwinjectAutoregistration#60]
Hello everybody,

How soon can you fix this problem? On Xcode 11.7 SwinjectAutoregistration works OK.

![Call_Stack](https://user-images.githubusercontent.com/2004963/93975330-83bd3a80-fda1-11ea-8e6c-a31dd8716951.png)
![Source_Code](https://user-images.githubusercontent.com/2004963/93975338-8586fe00-fda1-11ea-8465-b6b64dc75ba0.png)

**Comment by aknolldev** [comment]
Also seeing this issue after upgrading to XCode 12

**Comment by tkohout** [comment]
Could you provide some example project which would work on Xcode 11 and fail to resolve in Xcode 12?

Or at least the `autoregister` calls that register the failing services.

**Comment by aknolldev** [comment]
Hi @tkohout,
our project is confidential, so unfortunately I can only provide you modified excerpts. Hope this helps you anyway.

This is the autoregister call:
`container.autoregister(EnvironmentProvider.self, initializer: EnvironmentProviderImpl.init)`

EnvironmentProviderImpl looks like this:
```
import Foundation
import Shared

public struct EnvironmentProviderImpl: EnvironmentProvider {
    private enum Paths: String {
        case imprint = "imprint"

    }
    
    public var supportedAppliances: [ApplianceType] = [.applX, .applY, .applZ]
    
    public var environment: Environment {
        #if DEV
        return .dev
        #elseif STAG
        return .stag
        #elseif LIVE
        return .live
        #endif
    }
    
    private var locale: String {
        Locale.current.identifier
    }
}

public extension EnvironmentProviderImpl {
    var imprintURL: URL {
        baseRedirectURL.appendingPath(Path.imprint.rawValue)
    }

}
```

The project compiles and runs but right at the start, we get this error:
<img width="261" alt="swinject_auto_1" src="https://user-images.githubusercontent.com/68063119/94397981-f4c76e00-0164-11eb-8f14-885d4b479102.png">
<img width="921" alt="swinject_auto_2" src="https://user-images.githubusercontent.com/68063119/94397994-fb55e580-0164-11eb-99c1-941326de36ad.png">


Thanks for your help!

**Comment by tkohout** [comment]
@aknolldev Thanks for the example:

The problem is in this line:

```swift
public var supportedAppliances: [ApplianceType] = [.applX, .applY, .applZ]
```

If you have a **struct** that has a variable with a default value the compiler will create two inits, in you case it is:

`.init` and `.init(supportedAppliances:)`

For some reason, since the Swift 5.3 the compiler will pick the `.init(supportedAppliances:)` instead of `.init` which was selected in the older Swift. Swinject then tries to resolve `[ApplianceType]` which it can't find. Interestingly enough this will only happen if the struct has only one variable with default value. If you have e.g. 2 variables, it will work the same as in the old version.

In your case you have multiple ways to solve this error:

1. add your own empty init to your struct:
```
init() {}
```

2. force the use of the correct init in the registration code:
```
container.autoregister(EnvironmentProvider.self, initializer: EnvironmentProviderImpl.init as () -> EnvironmentProviderImpl)
```

3. rewrite you code not to you variable with default value
```
public var supportedAppliances: [ApplianceType] { [.applX, .applY, .applZ] }
```

**Comment by aknolldev** [comment]
Thanks @tkohout! We will go for option 2, it fits best for us and works perfectly fine. 👍
