### ISSUE TITLE
Reason for container.autoregister with max of 3 arguments only

### ISSUE THREAD

**Issue by loilee** [Swinject/SwinjectAutoregistration#65]
I am using container.autoregister with arguments to dynamically mock dependencies for unit testing.
However I find that the arguments parameter can only have max of 3, any reason why?

**Comment by tkohout** [comment]
The reason is combinatorics. We support 20 dependencies with 3 dynamic arguments. 

That means generating 60 `autoregister` functions. Having e.g. 5 arguments would mean generating 100 functions which further increases the size of the library.

You can try by cloning the repo and running `bin/generate 20 5`
